# This is a configuration file for the kickoff utility
ignore:
    - .kickoff.yml

questions:
    # A question object is a hash containing question related values:
    - 
        # type: (String) Type of the prompt.
        # Defaults: input - Possible values: input, confirm, list, rawlist
        type: input

        # name: (String) The name to use when storing the answer in the anwers hash.
        name: appname

        # message: (String) The question to print.
        message: The name of the application

        # default: (String|Number|Array|Function)
        # Default value(s) to use if nothing is entered,
        # or a function that returns the default value(s).
        # If defined as a function,
        # the first parameter will be the current inquirer session answers.
        default: anonymous

        # choices: (Array|Function) Choices array or a function returning a choices array.
        # If defined as a function,
        # the first parameter will be the current inquirer session answers.
        # Array values can be simple strings, or objects containing a name (to display)
        # and a value properties (to save in the answers hash).
        # Values can also be a Separator.

        # validate: (Function) Receive the user input and should return true
        #           if the value is valid, and an error message (String) otherwise.
        # If false is returned, a default error message is provided.

        # filter: (Function) Receive the user input and 
        #         return the filtered value to be used inside the program.
        # The value returned will be added to the Answers hash.

        # when: (Function) Receive the current user answers hash 
        #       and should return true or false depending on 
        #       whether or not this question should be asked.

    -
        type: input
        name: author_full_name
        message: The full name of the author of the application
        default: Anonymous

    -
        type: input
        name: author_email
        message: The email address of the author
        default: anonymous@some-domain.com

    -
        type: input
        name: author_github_account
        message: The github account (username) of the author
        default: anonymous
